# Alembic Configuration File
# Provides the template for Alembic to find migrations and configure logging.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
#file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# string value is passed to the constructor of datetime.datetime
# Leave blank for localtime
# timezone =

# max length of characters to apply to the
# "slug" field of the filename (template only)
# truncate_slug_len = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# logging configuration
# Loggers to configure
[loggers]
keys = root,sqlalchemy,alembic

# Handlers to configure
[handlers]
keys = console

# Formatters to configure
[formatters]
keys = generic

# root logger
[logger_root]
level = WARN
handlers = console
qualname =

# logger to use when running migrations
[logger_alembic]
level = INFO
handlers =
qualname = alembic

# logger to use when at console for database - when using -q option
# as user is asking to decrease verbosity by not showing all statements
# executed in INFO mode, but still show errors (WARN and above)
[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

# handler to invoke console output
[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

# default format for all log records
[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S

# A commonly useful setting is to set `sqlalchemy.url` to enable autogenerate
# of your models if your database supports it.
# In that case set:
# [sqlalchemy]
# sqlalchemy.url = driver://user:pass@localhost/dbname

[sqlalchemy]
# sqlalchemy.url = driver://user:pass@localhost/dbname
# Leave this blank; it will be set by env.py from settings.DATABASE_URL
